{
  "formatVersion": "1.1",
  "component": {
    "group": "com.extscreen.sdk",
    "module": "eskit-official",
    "version": "2.9.5-rc08",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.extscreen",
          "module": "hippy4tv-support",
          "version": {
            "requires": "1.9.124"
          }
        },
        {
          "group": "com.sunrain",
          "module": "utils",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-media-compat",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.7"
          }
        },
        {
          "group": "com.extscreen.runtime",
          "module": "runtime-api",
          "version": {
            "requires": "2.2-beta20"
          }
        },
        {
          "group": "org.java-websocket",
          "module": "Java-WebSocket",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "android.arch.persistence.room",
          "module": "runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.koushikdutta.async",
          "module": "androidasync",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "appcompat-v7",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "recyclerview-v7",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "tv.huan.app_update",
          "module": "app_update",
          "version": {
            "requires": "1.1.8"
          }
        }
      ],
      "files": [
        {
          "name": "eskit-official-2.9.5-rc08.aar",
          "url": "eskit-official-2.9.5-rc08.aar",
          "size": 2595177,
          "sha512": "ebfcbc1efabdf3ddb0fba7da197cd754c10eb4b1bfd8d31da53a31c342c1f66b34198a50fbfca4c0e2b062ccacb66d99db2553f74d7225c650b86d4d1651016b",
          "sha256": "943f5ccd200377896a76430cda6fb449b5515c2f59a3594b601f75819e361f9c",
          "sha1": "5c168180a6d0e9e683b579dbeda9110139bedb35",
          "md5": "52a85363f04ce745dec80a454cde66d9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.extscreen",
          "module": "hippy4tv-support",
          "version": {
            "requires": "1.9.124"
          }
        },
        {
          "group": "com.sunrain",
          "module": "utils",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-media-compat",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.7"
          }
        },
        {
          "group": "com.extscreen.runtime",
          "module": "runtime-api",
          "version": {
            "requires": "2.2-beta20"
          }
        },
        {
          "group": "org.java-websocket",
          "module": "Java-WebSocket",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "android.arch.persistence.room",
          "module": "runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.koushikdutta.async",
          "module": "androidasync",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "appcompat-v7",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "recyclerview-v7",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "tv.huan.app_update",
          "module": "app_update",
          "version": {
            "requires": "1.1.8"
          }
        }
      ],
      "files": [
        {
          "name": "eskit-official-2.9.5-rc08.aar",
          "url": "eskit-official-2.9.5-rc08.aar",
          "size": 2595177,
          "sha512": "ebfcbc1efabdf3ddb0fba7da197cd754c10eb4b1bfd8d31da53a31c342c1f66b34198a50fbfca4c0e2b062ccacb66d99db2553f74d7225c650b86d4d1651016b",
          "sha256": "943f5ccd200377896a76430cda6fb449b5515c2f59a3594b601f75819e361f9c",
          "sha1": "5c168180a6d0e9e683b579dbeda9110139bedb35",
          "md5": "52a85363f04ce745dec80a454cde66d9"
        }
      ]
    }
  ]
}
