{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sunrain",
    "module": "utils",
    "version": "1.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "ciizahnrsrgpxob3zoj3lzcxsu"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "utils-1.3.3.aar",
          "url": "utils-1.3.3.aar",
          "size": 540389,
          "sha512": "b6bacd551b2e49209a8c96673d8070d80153916e6bb270863115aa350f9f59e39ba0885a2e446022b3a8b8745b5dab339fcb6b6e8d5260e89e0552c23ecb2991",
          "sha256": "dd3e06d706fedf466044beea73eff88beeee86d7917e795c3cc886601da3dc9f",
          "sha1": "da77b8d535852f08a7d95d0d650cd429c4eb98e1",
          "md5": "07a828cc6f4caac26c22785ce69184c6"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "utils-1.3.3.aar",
          "url": "utils-1.3.3.aar",
          "size": 540389,
          "sha512": "b6bacd551b2e49209a8c96673d8070d80153916e6bb270863115aa350f9f59e39ba0885a2e446022b3a8b8745b5dab339fcb6b6e8d5260e89e0552c23ecb2991",
          "sha256": "dd3e06d706fedf466044beea73eff88beeee86d7917e795c3cc886601da3dc9f",
          "sha1": "da77b8d535852f08a7d95d0d650cd429c4eb98e1",
          "md5": "07a828cc6f4caac26c22785ce69184c6"
        }
      ]
    }
  ]
}
