{
  "formatVersion": "1.1",
  "component": {
    "group": "eskit.sdk.support",
    "module": "small-player-support",
    "version": "1.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "small-player-support-1.1.0-SNAPSHOT.aar",
          "url": "small-player-support-1.1.0-SNAPSHOT.aar",
          "size": 23838,
          "sha512": "4f79971dc1a6df0e32c86ce600e3b90f573d1520e49445ef87bcafab2641f73fb24f29df544255326dde992d028d49340413e856935108f3d36bbd428a7b7437",
          "sha256": "81ff93752827b64c24fd92779fa22bedfd95a0e54df1bb320fe9be51e5603d0c",
          "sha1": "15cdb526dae20af695210550f6ec35508971167f",
          "md5": "56ea5a4571471dc5158865158a88a854"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.support",
          "module": "recyclerview-v7",
          "version": {
            "requires": "28.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "small-player-support-1.1.0-SNAPSHOT.aar",
          "url": "small-player-support-1.1.0-SNAPSHOT.aar",
          "size": 23838,
          "sha512": "4f79971dc1a6df0e32c86ce600e3b90f573d1520e49445ef87bcafab2641f73fb24f29df544255326dde992d028d49340413e856935108f3d36bbd428a7b7437",
          "sha256": "81ff93752827b64c24fd92779fa22bedfd95a0e54df1bb320fe9be51e5603d0c",
          "sha1": "15cdb526dae20af695210550f6ec35508971167f",
          "md5": "56ea5a4571471dc5158865158a88a854"
        }
      ]
    }
  ]
}
