{
  "formatVersion": "1.1",
  "component": {
    "group": "eskit.sdk.support.so",
    "module": "hp-v1-arm64-v8a",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hp-v1-arm64-v8a-1.0.1.aar",
          "url": "hp-v1-arm64-v8a-1.0.1.aar",
          "size": 3282059,
          "sha512": "e15c19f2027b8b3be8bf82e27c3e3c43a12e951330d0e76a388aea3b514ba2689474c05b078ad87d9d7b79463d616936af82e3486d8358d1c735d7954f3ec431",
          "sha256": "b783ce2379b65ab82e4383283f8cd92e3c69bcf31a9d2981b6e6690b3cf15e1e",
          "sha1": "734943fa1105770840cc28fd10656a339275b499",
          "md5": "ed419f5dd6125914c6d621a90029df12"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hp-v1-arm64-v8a-1.0.1.aar",
          "url": "hp-v1-arm64-v8a-1.0.1.aar",
          "size": 3282059,
          "sha512": "e15c19f2027b8b3be8bf82e27c3e3c43a12e951330d0e76a388aea3b514ba2689474c05b078ad87d9d7b79463d616936af82e3486d8358d1c735d7954f3ec431",
          "sha256": "b783ce2379b65ab82e4383283f8cd92e3c69bcf31a9d2981b6e6690b3cf15e1e",
          "sha1": "734943fa1105770840cc28fd10656a339275b499",
          "md5": "ed419f5dd6125914c6d621a90029df12"
        }
      ]
    }
  ]
}
